In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("F:/Datasets/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [7]:
import pickle #used to carry a trained model and make predictions

In [8]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [9]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [10]:
mp.predict([[5000]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
import joblib #Used to carry large numpy arrays

In [13]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [14]:
mj = joblib.load('model_joblib')

In [15]:
mj.predict([[5000]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [16]:
mj.coef_

array([135.78767123])

In [17]:
mj.intercept_

180616.43835616432

# To check whether joblib is working correctly

In [18]:
if model.predict([[5000]]) == mj.predict([[5000]]):
    print("Joblib is working correctly")
else:
    print("Joblib is not working correctly")

Joblib is working correctly


C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
