In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [3]:
import pandas as pd
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=10)

In [5]:
len(X_train)

1257

In [6]:
len(X_test)

540

## Logistic Regression

In [7]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [8]:
lr.score(X_test,y_test) * 100

95.92592592592592

## Support Vector Machine

In [9]:
svm = SVC()
svm.fit(X_train,y_train)

SVC()

In [10]:
svm.score(X_test,y_test) * 100

98.33333333333333

## Random Forest Classifier 

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [12]:
rf.score(X_test, y_test) * 100

97.03703703703704

# K-Fold

In [13]:
from sklearn.model_selection import KFold

In [15]:
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):  #Working of K_Fold
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test) * 100

## Scores of the previous models

In [19]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test) #Logistic Regression

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


95.92592592592592

In [20]:
get_score(SVC(),X_train,X_test,y_train,y_test) #Support Vector Machine

98.33333333333333

In [21]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test) #RandomForestClassifier

97.03703703703704

## Cont.

In [22]:
from sklearn.model_selection import StratifiedKFold

In [23]:
folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logisti

In [25]:
scores_lr

[92.32053422370618, 94.15692821368948, 91.48580968280467]

In [26]:
scores_rf

[92.65442404006677, 95.82637729549248, 92.65442404006677]

In [27]:
scores_svm

[96.661101836394, 98.1636060100167, 95.49248747913188]

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(LogisticRegression(),digits.data,digits.target) * 100

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logisti

array([92.22222222, 86.94444444, 94.15041783, 93.8718663 , 89.69359331])

In [30]:
cross_val_score(SVC(),digits.data,digits.target) * 100

array([96.11111111, 94.44444444, 98.32869081, 98.88579387, 93.8718663 ])

In [31]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target) * 100

array([93.88888889, 91.94444444, 95.82172702, 96.37883008, 92.2005571 ])