In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv('F:/Datasets/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

DATA PREPROCESSING

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [8]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
reg.intercept_

383724.9999999998

PREDICTION

In [12]:
reg.predict([[3000,3,40]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [16]:
# CHECK
# PRICE = m1*area+m2*bedrooms+m3*age+b
price = 137.25*3000 + -26025*3 + -6825*40 + reg.intercept_
price

444399.9999999998

In [13]:
reg.predict([[5000,4,15]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([863500.])

In [14]:
reg.predict([[10000,15,1]])

C:\Users\PRABHAKAR VENKAT\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1359025.])